### ISSUE TITLE
Add API endpoint to return number of card IDs

### ISSUE THREAD

**Issue by l0gik** [allhandsactive/door-api#191]
To help with more accurate memory allocation in the JSON parser, it would be useful to know ahead of time how many card IDs are being given to us when we call the /user endpoint.  Something like this should suffice:

```JSON
{
  "numCards": 4,
  "cardIds": [
    "01020304",
    "05060708",
    "09101112",
    "13141516"
  ]
}
```

**Comment by l0gik** [comment]
After working with the JSON stuff a bit more, I realize this isn't going to pan out the way I envisioned.  However, what could help is to have a separate API endpoint(s) to get some generic info about the card DB, such as the aforementioned number of cards, and/or last DB update timestamp (so we know if we should even bother to download the list at all based on our cache timestamp).  We could call this endpoint "/dbInfo" or something.

**Comment by artlogic** [comment]
https://github.com/allhandsactive/door-api/commit/68b47c793edc7b25655ef96482edf7d1610b072c

**Comment by artlogic** [comment]
https://github.com/allhandsactive/door-api/commit/fb95f0f8a8ae4fb42dc1b8d8f7eaf19302fe5e38
